### 로그인
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "email": "gangmini94@naver.com",
  "password": "1234"
}

### 로그인 후 접속시도

GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnYW5nbWluaTk0QG5hdmVyLmNvbSIsImF1dGgiOiJTVFVERU5UIiwiaWF0IjoxNjg4NjEzNjc2LCJleHAiOjE2ODg3MDAwNzZ9.8RxL0gnpBk4z-zocBXcAFHc40L2q9-EGDEPz9CCFztlSG1lrdbcTxWpB9FLXn2rl0DxC2RFShpZ8ErScYgNl8A


### ACCESS토큰 만료시

POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refresh_token" : "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnYW5nbWluaTk0QG5hdmVyLmNvbSIsImF1dGgiOiJTVFVERU5UIiwiaWF0IjoxNjg4NTY4MjY0LCJleHAiOjE2ODkxNzMwNjR9.eKgkg2MH6mOnmzmVNLrER8-VyOsUq_NIID2XLSQHAaOdT67ZrJnBUgQhR54KweMdG2AfZnzBuovDnhT3geB5Qw"
}